### ISSUE TITLE
iOS Build Failed... CompileC... /RCTMGLStyle.o RCTMGL/RCTMGLStyle.m

### ISSUE THREAD

**Issue by creimers** [nitaliano/react-native-mapbox-gl#1020]
I'm on xcode 9.1.

From my `package.json`:
```
"@mapbox/react-native-mapbox-gl": "^6.0.3-rc1",
"react": "16.2.0",
"react-native": "0.52.2",
```

It seems to me I am time and again running into the following build error **AFTER** having installed another react-native package that requires a `react-native link` setup.

```
CompileC /path/to/app/ios/build/Build/Intermediates.noindex/RCTMGL.build/Debug-iphonesimulator/RCTMGL.build/Objects-normal/x86_64/RCTMGLStyle.o RCTMGL/RCTMGLStyle.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```
It has happened to me both with [react-native-device-info](https://github.com/rebeccahughes/react-native-device-info) and [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation).

If I initialise a fresh project with `react-native init` and install react-native-mapbox-gl, it does work just fine.

Any ideas on what could be going on here?

**Comment by nitaliano** [comment]
@creimers yes I do know what is happening `react-native link` will attempt to link every single react native library and which only works for libraries that require very simple installation steps without other native packages. From now on I would recommend running `react-native link {packageName}` so it only attempts to link a specific package instead of all of them.

What `react-native link` is doing to this library is trying to link our native Mapbox SDK which requires `Mapbox.framework` to be embedded in the xcode project which is causing this error.

Going to close this out, if you need help unlinking let me know

**Comment by creimers** [comment]
@nitaliano 

I should have been clearer: I **do** run `react-native link {packageName}` before running into the described error. 

To summarize:
* manual iOS setup of react-native-mapbox-gl --> works just fine.
* subsequent `react-native link {packageName}` --> `**BUILD FAILED** CompileC...`
