### ISSUE TITLE
A visible RasterLayer on Mapbox Studio which can't set visibility: none. It will make app crashing.

### ISSUE THREAD

**Issue by phuochau** [nitaliano/react-native-mapbox-gl#1025]
Hi,

Currently, I have a `RasterLayer` called `my-markers` in my Mapbox Style, it has `visibility: visible`. But in programming, when I set its style with `visibility: none`, It will make app crashing, you can see error in screenshot:

![RasterLayer issue](https://i.gyazo.com/9b11862558149d5a0319aa4b1c9490b3.png "RasterLayer issue")

`visibility` is supported on `RasterLayer`, see in docs: https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/RasterLayer.md

So how can we hide it, thanks!

P/S: `rasterOpacity=0` does not work too.

**Comment by nitaliano** [comment]
We have this [example](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/WatercolorRasterTiles.js) where `rasterOpacity` does work. For some reason it seems to be thinking your layer is a `SymbolLayer` instead of a `RasterLayer` could you post a snippet of code that shows me how you're rendering your layers so I can debug it further. Is it possible that you have named a `SymbolLayer` and `RasterLayer` with the same id?

**Comment by phuochau** [comment]
@nitaliano Seem I'm wrong by my side, Because my layers are `SymbolLayer` and `LineLayer`. for iOS, they can cast but for Android, it can't so it make app crashing. After I changed to use `SymbolLayer` and `LineLayer`, it's working fine.
