### ISSUE TITLE
SymbolLayer svg icons

### ISSUE THREAD

**Issue by Pierre-Green** [nitaliano/react-native-mapbox-gl#1064]
Hello,

I would like to know how can I use svg icons from the icon property of the SymbolLayer.

Thank you :D

**Comment by nitaliano** [comment]
When you say svg icons do you mean the ones from studio or an actual svg?

**Comment by Pierre-Green** [comment]
From a SVG file

**Comment by Pierre-Green** [comment]
I've founded this: https://github.com/mapbox/spritezero is it working for react native ?

**Comment by nitaliano** [comment]
no spritezero won't work on react native because the native code needs to handle file processing, that's all done in node.

You can upload your images to your map style in studio and be able to reference them that way, or use `spritezero` as an npm script in your project so you can generate images before you start the project and reference them way. svg icons are not supported out of the box with `gl-native` and this repo probably shouldn't add support for it

**Comment by Pierre-Green** [comment]
Okay thank you very much :+1:
