### ISSUE TITLE
[iOS] Incompatibility with Unity

### ISSUE THREAD

**Issue by JasonPan** [nitaliano/react-native-mapbox-gl#1072]
I noticed after integrating MapBox into my project that my Unity view stops rendering. Even if I remove the map view from the screen, Unity still is unable to render content onto the screen (screen is black). I have to restart the app completely for the Unity view to load again.

The only "workaround" I have been able to find is to load the map slightly after the Unity view has been loaded (about 1 second). However, when React Native causes a re-render of the components on the screen, the Unity view stops working.

The only underlying cause I can think of is the fact that both MapBox and Unity use OpenGL under the hood. Unfortunately, I can't use Metal for Unity as one of my Unity dependencies only supports OpenGL. I've tried contacting Unity for support but am unsure which component is at fault here.

**Comment by nitaliano** [comment]
is there any reason why you wouldn't be using our Unity SDK here? I don't believe this is a supported use case, when we have time we can look into this more. I'm going to close this out for now since we would recommend using our unity SDK here.

We'll still mess around with this use case internally and if we do find a path forward we can reopen this issue and implement it.
