### ISSUE TITLE
"onRegionWillChange" isn't called on android

### ISSUE THREAD

**Issue by stanshivam** [nitaliano/react-native-mapbox-gl#1116]
I am trying to call onRegionWillChange but it never gets called. 
```
<Mapbox.MapView
              styleURL={Mapbox.StyleURL.Street}
              centerCoordinate={this.state.coordinates}
              onDidFinishRenderingFrameFully={this.onDidFinishRenderingFrameFully}
              onRegionWillChange={this.onRegionWillChange}
              onRegionDidChange={this.onRegionDidChange}
              zoomLevel={11}
              ref={(c) => this._map = c}
              onPress={this.onPress}
              style={styles.map}
          > 
          
</Mapbox.MapView>
```
`onRegionWillChange = () => console.log('region will change!')`

**Comment by nitaliano** [comment]
It's should be fixed already on master there was a typo in the event name

**Comment by stanshivam** [comment]
Its not bieng called in my case, rest all the event are bieng triggered like  onRegionDidChange, onDidFinishRenderingFrameFully etc. 

```
"@mapbox/react-native-mapbox-gl": "^6.1.0",
"react-native": "0.53.3",
```

The following two event are not working for me in android.
1. onRegionWillChange
2. onRegionIsChanging

**Comment by nitaliano** [comment]
yup you're not on master that's `6.1.0` `onRegionIsChanging` is not called unless you fling the map on Android due to an issue on the native Android SDK.

This is the PR that fixed `onRegionWillChange` https://github.com/mapbox/react-native-mapbox-gl/pull/1105 it will be in the next npm release.

We also might try to polyfill `onRegionIsChanging` on in our React Native codebase to workaround the native sdk not matching what the iOS SDK does with events

**Comment by zasyadev** [comment]
So I need to be on master, in order to get onRegionIsChanging working. Thanks. 
How can I switch from 6.1.0 to master?

**Comment by stanshivam** [comment]
okay thanks for the information. But in [#1105](https://github.com/mapbox/react-native-mapbox-gl/pull/1105) it says the PR fixes issue with onWillStartLoadingMap, not onRegionWillChange. Let me know if I am wrong.

Anyway I tried using` "@mapbox/react-native-mapbox-gl": "https://github.com/mapbox/react-native-mapbox-gl.git#master",` as the dependency but still onRegionWillChange is not getting called.  Is there anything else I need to do?

**Comment by KalebMatthews** [comment]
I manually added in both of the solutions mentioned here (#1105 and #1120) and I am still running into this issue on a physical device for android. The same code works perfectly on iOS. Is there a timeline for when this issue will be resolved?

**Comment by nitaliano** [comment]
There's a typo in the Android code and we need to figure out how to debounce it since it fire's constantly, I already started working on it so sometime soon we'll see a PR

https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java#L70 we're missing an L

**Comment by nitaliano** [comment]
@KalebMatthews try this PR out https://github.com/mapbox/react-native-mapbox-gl/pull/1132

**Comment by nitaliano** [comment]
It's been merged into master closing this out, please reopen if you run into any issues
