### ISSUE TITLE
Multiple Polygons Not Rendering

### ISSUE THREAD

**Issue by WarrenBuffering** [nitaliano/react-native-mapbox-gl#1370]
**Trying to build for iOS. Currently running:** 
"@mapbox/react-native-mapbox-gl": "^6.1.3",
"react": "16.3.1",
"react-native": "0.55.4",

I've tried MultiPolygon, individual features with "FeatureCollection", and even running the specific source code for SmileyFace in the documentation (GeoJSONSource.js and the smiley_face.json), but the polygon's won't render to the screen. Can you look into this?

**Comment by kristfal** [comment]
This is may be an implementation issue and not an issue with the underlying framework since its used in production by many apps. I suggest:

1) Try to build and run the example app. There are multiple examples using FeatureCollections and polygons. Review this code vs yours. Any differences?
2) If you still have an issue, please post your code
