### ISSUE TITLE
Map not firing events on Android on First Launch of app

### ISSUE THREAD

**Issue by MapYourShow** [nitaliano/react-native-mapbox-gl#1383]
I am having issues with the onPress and onWillStartLoadingMap events not being fired on Android when opening then app for the first time. This is not an issue once the app is closed and restarted. Not sure what is going on or how to get around it. We are using v6.1.3 currently. Not sure if anyone is having any similar issues or not.

**Comment by 386sx** [comment]
Probably related to #1380

**Comment by beisert1** [comment]
We were using the react-native-restart package which was breaking the events on Android when that package initiated a restart.

**Comment by TheCodeDestroyer** [comment]
@beisert1 Hey man I see you posting on all these issues with events not being processed. How did you figure out which lib caused the issue?

**Comment by beisert1** [comment]
@TheCodeDestroyer We knew something changed in our project that broke the events because they were working fine on a previous release of ours. I narrowed it down to the react-native-restart package by observing when the package initiated a restart is when the events broke. Removing the package or not initiating a restart fixed the events on Android.

**Comment by TheCodeDestroyer** [comment]
@beisert1 Which means that Live Reload probably breaks the events also...

**Comment by ricardodrs** [comment]
Same issue here =(

**Comment by TheCodeDestroyer** [comment]
@ricardodrs update your lib to master or to this commit 937977ef573c7bd4ae69972720eb1ec9fd8b6be9

**Comment by ricardodrs** [comment]
@TheCodeDestroyer thx guy!!!

**Comment by kristfal** [comment]
Fixed in master.
