### ISSUE TITLE
[Android] onUserLocationUpdate doesn't fire sometimes

### ISSUE THREAD

**Issue by alisherakb** [nitaliano/react-native-mapbox-gl#1569]
Quite often onUserLocationUpdate event doesn't work on Android.
The iOS app works ok.

"react-native": "^0.57.3",
"@mapbox/react-native-mapbox-gl": "https://github.com/mapbox/react-native-mapbox-gl.git#master"

**Comment by kristfal** [comment]
This is likely upstream issue with mapbox-gl-native or an issue with the android device/emulator itself. In order to determine this, you'll need to provide more info. Ex:

Device type (or emulator?)
Does other apps (Ex: google maps) get location updates?
Are you indoors?
Are you moving?
Are permissions correctly set?

Due to lack of issue details, I'll close this. Feel free to reopen if you can provide additional info.

**Comment by alisherakb** [comment]
> This is likely upstream issue with mapbox-gl-native or an issue with the android device/emulator itself. In order to determine this, you'll need to provide more info. Ex:
> 
> Device type (or emulator?)
> Does other apps (Ex: google maps) get location updates?
> Are you indoors?
> Are you moving?
> Are permissions correctly set?
> 
> Due to lack of issue details, I'll close this. Feel free to reopen if you can provide additional info.

Device type (or emulator?)
- Samsung S8.
Does other apps (Ex: google maps) get location updates?
- Yes, google maps get location updates.
Are you indoors?
- Indoors.
Are you moving?
- No.
Are permissions correctly set?
- Yes, otherwise it would not work sometimes. It happens occasionally.

**Comment by alisherakb** [comment]
@kristfal Any updates?
