### ISSUE TITLE
Child/Subview Support?

### ISSUE THREAD

**Issue by brianjd** [nitaliano/react-native-mapbox-gl#179]
Was attempting to do something like the following:

``` xml
<Mapbox>
     <View />
</Mapbox>
```

View appears for half a second then appears to get rendered over.  Is this an actual bug, or am I implementing incorrectly?

**Comment by bsudekum** [comment]
What's the use case here?

**Comment by brianjd** [comment]
Cases where you want to add map specific nested views (ie. map controls).  In my specific scenario, I have an animated view adjacent to the mapview.  Being able to nest map specific views/controls simplifies animations, and eliminates the need to do some weird calculations to re-center/position when the adjacent resizes.  Compared to when you try to just layer views on top, and try to give the illusion that the mapview resized.

**Comment by jrnk** [comment]
+1 We need to have a 'compass' view on top of the map at the user location, that points and rotates to annotations (instead of north). Currently, I can't think of a way to do this.

**Comment by rmevans9** [comment]
Another use case I have is I need to have the map behind a nav bar of sorts. The nav bar is semi transparent so you can see the top part of the map through it. More of an aesthetic use case

**Comment by rajkissu** [comment]
+1, would simplify nesting of map controls, as opposed to workarounds with absolute positioning to prevent the map from rendering over child components.

**Comment by maqen** [comment]
Is there any current way to have views on top of mapbox map on android? Trying to use same solution with absolute positioning as used on iOS but to no avail.

Any tips on how to add a button overlayed on android?

**Comment by dapetcu21** [comment]
I still don't see the usecase. For most cases where you'd need map controls, you'd have to use absolute positioning anyway with the children to put the map control in a corner. 

While the talk about having components on the actual map at a specified set of coordinates goes into the separate discussion about annotation views.

Anyway, this can easily be done with a higher order component:

``` jsx
const MapViewWithChildren = ({ children, style, ...otherProps }) => (
  <View style={{ position: 'relative' }}>
    <MapView style={[{ flex: 1, alignSelf: 'stretch' }, style]} {...otherProps} />
    <View style={{ position: 'absolute', top: 0, bottom: 0, left: 0, right: 0 }}>
      {{ children }}
    <View>
  </View>
);
```

**Comment by tlvenn** [comment]
Hi @dapetcu21 ,
Here is a valid usecase that cant be solved by just layering on top of MapBox component:
![pasted image at 2016_10_13 12_04 am](https://cloud.githubusercontent.com/assets/3340262/19340084/ac34c6ee-9159-11e6-82b4-aa02b587aabc.png)

So the circle need to be static over the map, it should not move as you pan the map. Its radius is dynamic depending of the zoom level. The other annotations are geo based and need to be overlaid on top of the circle so that the circle semi transparent background is not visible on those annotations.

Currently unless I am missing something, we either can have a static circle with no background color or leverage annotation to draw a circle underneath the other annotations but it will move as you pan the map, which is what we currently end up doing.

**Comment by dapetcu21** [comment]
Yes, true. But I don't think Mapbox GL lets you draw stuff between the map and the annotations anyway.

**Comment by tlvenn** [comment]
This issue upstream https://github.com/mapbox/mapbox-gl-native/issues/6570 makes reference of one way I believe:

> it's currently possible for users to add views to the view hierarchy through MapView#addView and listen to mapchange events
