### ISSUE TITLE
Enable `always` location permissions and background location

### ISSUE THREAD

**Issue by friedbunny** [nitaliano/react-native-mapbox-gl#190]
Mapbox terms of service and [mobile telemetry](https://www.mapbox.com/telemetry/) require that `always` location permissions be granted and background location be enabled for most developers' apps. 

On iOS, this is blocked by facebook/react-native#1506 — react-native currently will only ever ask for `whenInUse` permissions.

/cc @bsudekum @mapbox/mobile

**Comment by rmevans9** [comment]
Technically you can use always location permissions... just not with React-Native's geolocation implementation. You can however use third party ones like https://github.com/timfpark/react-native-location. The catch is in the JS side of things you will not be able to execute code while the screen is off (due to the bug you point out). However since Mapbox is actually running natively anything that it does internally upon location updates can still execute it just won't trigger any calls across the RN bridge meaning any custom logic a user may have on location updates won't execute. 

Given that Mapbox's internal location update logic would be executing does that meet the requirements of the ToS and mobile telemtry?

**Comment by 1ec5** [comment]
Requesting always access is one thing, but the request will never succeed unless `NSLocationAlwaysUsageDescription` is set in the Info.plist. Even native code won’t run unless background location is enabled for the application (again via Info.plist).

**Comment by rmevans9** [comment]
What is preventing you from adding that to the info.plist? I have added that and it works as expected.

**Comment by dapetcu21** [comment]
Is this still the case? I can't find that requirement in the ToS. Also, from the iOS docs:

> In order to show the user’s position on the map, you must first ask for their permission. In iOS 8 and above, this is accomplished by creating and setting the `NSLocationAlwaysUsageDescription` **and/or** `NSLocationWhenInUseUsageDescription` keys in the Info.plist file.

Which leads me to believe it's acceptable to just use `NSLocationWhenInUseUsageDescription`.

**Comment by 1ec5** [comment]
You’re correct, our ToS has changed since the issue was originally filed. Furthermore, the upstream issue was fixed in facebook/react-native#5093.
