### ISSUE TITLE
Customize displaying of current user location

### ISSUE THREAD

**Issue by aksonov** [nitaliano/react-native-mapbox-gl#274]
Is it possible to change radius, shape, color, animation?

**Comment by tmcw** [comment]
Currently not: the [showUserLocation option is set as a simple boolean on the underlying mapbox-gl-native implementation](https://github.com/mapbox/react-native-mapbox-gl/blob/7899a3d01cb7510a76a1c3414afba68b5b3b3e15/ios/RCTMapboxGL/RCTMapboxGL.m#L77).

The upstream issue for supporting custom annotations there is: https://github.com/mapbox/mapbox-gl-native/issues/1784

**Comment by 1ec5** [comment]
The upstream issue to watch is now mapbox/mapbox-gl-native#5037.

**Comment by olliepop** [comment]
Looks like this is implemented now, any chance it can make it in?

https://github.com/mapbox/mapbox-gl-native/issues/5037

**Comment by 1ec5** [comment]
mapbox/mapbox-gl-native#1784 was for representing an annotation _other than_ the user location annotation as a native UIView. (#404 tracks adopting that in RNMBGL.) View-backed annotations are a prerequisite for mapbox/mapbox-gl-native#5037, which allows developers to provide their own native UIView for the user location annotation as well.

The fix for mapbox/mapbox-gl-native#5037 is in an alpha release of Mapbox iOS SDK v3.4.0. Developers are encouraged to try out this SDK release and report issues. However, new features (particularly runtime styling) haven’t stabilized enough to begin developing against the new version – that’ll come with the first beta release, due soon. If someone is interested in getting a head start on the RNMBGL changes that’ll be needed to support this new feature, now would be a good time to start, and pull requests are welcome.

Unfortunately, the same challenge described in https://github.com/mapbox/react-native-mapbox-gl/issues/404#issuecomment-247819536 apply to custom user location annotations as well. If that challenge proves to be insurmountable, perhaps RNMBGL can offer an expanded range of options (providing its own MGLAnnotationView subclass) in lieu of full custom view support.

In the meantime, if you need a custom user location annotation and don’t mind writing your application in (truly) native iOS technologies, I’d recommend using the Mapbox iOS SDK directly in Objective-C or Swift.

**Comment by timfpark** [comment]
I would like to display a directional current user location, like what Google Maps does when you are navigating a route, that includes a compass direction heading to enable the user to determine which direction they are facing relative to the route.  Will the enhancement that is described here enable that?

**Comment by 1ec5** [comment]
@timfpark, what you’re describing sounds like the existing `userTrackingMode` option, specifically `Mapbox.userTrackingMode.followWithCourse` or `Mapbox.userTrackingMode.followWithHeading`.

**Comment by timfpark** [comment]
Thanks @1ec5 - I'll file a separate bug for that since it doesn't seem to work for me with 5.1.0.
