### ISSUE TITLE
Update this project to use new Mapbox styles

### ISSUE THREAD

**Issue by shvetusya** [nitaliano/react-native-mapbox-gl#354]
I am trying to use new awesome outdoors maps in my React native application.

From what I understand this library does not support url styles for maps because it is not up to date with
https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.2.2.

I tried to fork it and update mapbox-gl but unfortunately have pretty limited knowledge of native development. Also search path for mapbox is in `/Users/bobby/Downloads/mapbox-gl-ios-0.2.17`.

If someone could outline what steps are required to make an upgrade I could try to make a pull request.

**Comment by bsudekum** [comment]
You can actually reference any style, not just the ones which are provided as constants. To use the outdoor style, you'd do something like 

```
styleURL={'mapbox://styles/mapbox/outdoors-v9'}
```

**Comment by tmcw** [comment]
@bsudekum thoughts on removing the constants? Users applications could easily define their own constants if they want.

**Comment by bsudekum** [comment]
@tmcw what would this look like? I'm thinking this should only mirror constants provided by mapbox-gl-native.

**Comment by tmcw** [comment]
I don't think the parallel to mapbox-gl-native really works: in native, constants are used because static type-checking is guaranteed on the language level. Unless you use Flow or TypeScript, there's no real advantage to using constants in JS, and it's just as easy to make a typo with them as with a string. For devs who _are_ using Flow, I think providing their own contants is perfectly fine.

Some relevant, I'm also very much in favor of de-emphasizing constants in gl-native too. They're a best-practice that devs quickly and incorrectly assume are the only way to refer to styles. They're just string constants, and I think we should prefer strings and only encourage constants for people who really, really want to do a best-practice.

**Comment by shvetusya** [comment]
Thank you for clarification. Didn't realize that style can be a string. Closing this.
