### ISSUE TITLE
onStartLoadingMap/onFinishLoadingMap not fired

### ISSUE THREAD

**Issue by Biboba** [nitaliano/react-native-mapbox-gl#383]
Hi, 
I am using react-native-mapbox-gl 5.0.0 on Android and it seems like the 2 events, onStartLoadingMap/onFinishLoadingMap are not firing.

Here is the code sample:

onFinishLoadingMap = () => {
    console.log('map loaded');
  };
  onStartLoadingMap = () => {
    console.log('map start loading');
  };

And in the view:
          ...
          onFinishLoadingMap={this.onFinishLoadingMap}
          onStartLoadingMap={this.onStartLoadingMap}

Do you confirm ?

Cheers

**Edit:**
onFinishLoadingMap does start using mapbox style (Mapbox.mapStyles.dark) but not with a custom one.

**Comment by dapetcu21** [comment]
Indeed, I can confirm `on{Start,Finish}LoadingMap` doesn't get called on Android. I'll try to see why.

**Comment by dapetcu21** [comment]
After some debugging, I can confirm `onStartLoadingMap` doesn't get called initially because the event happens before I get a chance to attach an event listener to it. I'll create an issue upstream about this.

I can not confirm, though, that `onFinishLoadingMap` doesn't get called when using a custom map. Is there anything else happening in your setup that might affect this? Maybe an offline pack with that style?

**Comment by nolan-m** [comment]
Any update on this?  Seems like Android only fires onStartLoadingMap the first time the map mounts.  Any other time you navigate to the screen with the map, this is not fired.

**Comment by luskin** [comment]
I am seeing this issue as well. The very first time the map is loaded everything works fine, however after that these callbacks are not fired thus my map doesn't fade in as expected. I know this is closed but does anyone have any relevant information?
