### ISSUE TITLE
getOfflinePacks is not working on ios

### ISSUE THREAD

**Issue by HananeAlSamrout** [nitaliano/react-native-mapbox-gl#389]
hello, after executing "addOfflinePackForRegion" on ios and android, i want to retrieve it somewhere in the app using "getOfflinePacks",

 Mapbox.getOfflinePacks()
      .then(packs => {
        console.log('packs', packs);
      })
      .catch(err => {
        console.error(err); // Handle error
      })

on android, i am getting packs,  but not on ios.

**Comment by dapetcu21** [comment]
Will look into it and see if I can reproduce.

**Comment by timfpark** [comment]
I'm seeing the same on 5.0.0 on iOS.

**Comment by sslash** [comment]
Same here. It just hangs, the promise never resolves or rejects

**Comment by 1ec5** [comment]
I suspect this is happening because MGLOfflineStorage has already been created by the time [RCTMapboxGLManager begins observing](https://github.com/mapbox/react-native-mapbox-gl/blob/66960a6729793294375031ffed0d34d534861014/ios/RCTMapboxGL/RCTMapboxGLManager.m#L150) for changes to `MGLOfflineStorage.packs`, so the `packs` array has already been populated and won’t ever change for the observer to be notified. The fix, then, is to specify `NSKeyValueObservingOptionInitial` as an option when [adding the observer](https://github.com/mapbox/react-native-mapbox-gl/blob/66960a6729793294375031ffed0d34d534861014/ios/RCTMapboxGL/RCTMapboxGLManager.m#L150) ([example](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.3.4/platform/ios/app/MBXOfflinePacksTableViewController.m#L37)). Some of the early returns in `-observeValueForKeyPath:ofObject:change:context:` may need to be modified to allow the callback to be called in this situation.

/cc @bsudekum

**Comment by ddolheguy** [comment]
Do we know when this might be resolved?

**Comment by ikalafat** [comment]
I'm seeing this issue, too.

**Comment by f1qwase** [comment]
The same for me on iOS 10.1
