### ISSUE TITLE
How to let a annotation at the top of others

### ISSUE THREAD

**Issue by santong** [nitaliano/react-native-mapbox-gl#411]
I tried to let the annotation be the first/last one of annotations array. But it does not work.

Or the annotations rendering sequence is according to `id`?

**Comment by 1ec5** [comment]
Are you seeing this issue on Android or iOS?

The `annotations` array’s order should determine the drawing order, with the last element in the array being drawn on top. There was at one point a regression causing the order to not be respected: mapbox/mapbox-gl-native#5710. The fix for that bug made it into Mapbox iOS SDK v3.3.1, which RNMBGL requires; however, it didn’t make it into the Mapbox Android SDK until v4.2.0-beta.1. If you’re seeing this issue on Android, perhaps you could try manually upgrading to a 4.2.0 beta.

/cc @zugaldia
