### ISSUE TITLE
Shader compilation crashes on Android emulators

### ISSUE THREAD

**Issue by almithani** [nitaliano/react-native-mapbox-gl#415]
After upgrading to react native 0.32 (from 0.26), I started to experience crashes on my Android emulator when displaying a map.  I had been using Android SDK Tools 25.2.2, but downgraded to 25.1.7 and am now about to display the map successfully on my emulator.

Here's the relevant Android Monitor output:

```
09-14 12:11:26.477 3674-3674/com.MyMapProj E/mbgl: [Shader]: Shader failed to compile: ERROR: Valid GLSL but not GLSL ES
09-14 12:11:26.477 3674-3674/com.MyMapProj E/mbgl: [Shader]: Vertex shader fill failed to compile: precision highp float;
                                                  #ifdef GL_ES
                                                  precision highp float;
                                                  #else
                                                  #define lowp
                                                  #define mediump
                                                  #define highp
                                                  #endif

                                                  attribute vec2 a_pos;

                                                  uniform mat4 u_matrix;

                                                  void main() {
                                                      gl_Position = u_matrix * vec4(a_pos, 0, 1);
                                                  }
09-14 12:11:26.477 3674-3674/com.MyMapProj A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadcab1 (code=1), thread 3674 (com.MyMapProj)
09-14 12:11:26.747 1130-1130/? E/Corkscrew: unrecognized dwarf lower part encoding: 0x22
09-14 12:11:26.897 1567-1599/system_process E/InputDispatcher: channel '9d37e248 com.MyMapProj/com.MyMapProj.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by 1ec5** [comment]
This sounds like mapbox/mapbox-gl-native#5878.

**Comment by mgtitimoli** [comment]
Hi,

I'm experiencing the same... Has someone found a workaround to use while we get to a final solution?

Thanks!

**Comment by almithani** [comment]
@mgtitimoli My comment above mentions that downgrading Android SDK Tools worked for me.  Did you try that?

**Comment by mgtitimoli** [comment]
thanks @almithani, no I haven't yet, it can't be done using the sdk manager, so I was looking for the link to download it manually... Which is your current setup, so I try with that one?

**Comment by almithani** [comment]
@mgtitimoli http://dl-ssl.google.com/android/repository/tools_r25.1.7-macosx.zip

**Comment by mgtitimoli** [comment]
(Thanks @almithani! Map is alive again...)

 I can confirm this setup is working in case anyone is experiencing the same (there is no way to downgrade tools and platform tools, this is why I'm leaving all the links to download them manually and unzip it directly in your installation folder):
1. [Android SDK **version 24.4.1**](https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz)
   - this one is the entire SDK, I'm leaving it here in case you want to start from scratch, otherwise you can use what you already have and overwrite the specific folders with the packages specified below
2. [Tools **version 25.1.7**](https://dl.google.com/android/tools_r25.1.7-linux.zip)
3. [Platform Tools **version 23.1.0**](https://dl.google.com/android/platform-tools_r23.1.0-linux.zip)
4. [Android Support Repository (extras) **version 38**](https://dl.google.com/android/android_m2repository_r38.zip)
   - this one goes under **$ANDROID_HOME**/extras/android
5.  Available to download directly using SDK Manager (android sdk)
   - Android SDK Build-tools **version 23.0.3**
   - Android SDK Build-tools **version 23.0.2**
   - Android SDK Build-tools **version 23.0.1**
   - Android 6.0 (API 23)
     - SDK Platform **version 23.3** 
     - Google APIs Intel x86 Atom_64 System Image **version 23.16**

Hope this issue gets resolved soon...

**Comment by 1ec5** [comment]
Now tracking upstream in mapbox/mapbox-gl-native#6400.

**Comment by uudruid74** [comment]
Try running the emulator with -gpu swiftshader, like this:
LD_PRELOAD='/usr/lib64/libstdc++.so.6' emulator -no-boot-anim -netdelay none -netspeed full -avd Nexus_5_API_22_x86 -gpu swiftshader -qemu -m 1526

**Comment by Hahihula** [comment]
The downgrade sadly don't worked for me ... it still crashes even the example app on emulator, bud on physical device it works ... 
I only write here with working link to the platform tools 25 because the link by @mgtitimoli seems to be dead:
linux:
[http://dl-ssl.google.com/android/repository/platform-tools_r25-linux.zip](http://dl-ssl.google.com/android/repository/platform-tools_r25-linux.zip)
windows:
[http://dl-ssl.google.com/android/repository/platform-tools_r25-windows.zip](http://dl-ssl.google.com/android/repository/platform-tools_r25-windows.zip)
macos:
[http://dl-ssl.google.com/android/repository/platform-tools_r25-macosx.zip](http://dl-ssl.google.com/android/repository/platform-tools_r25-macosx.zip)

**Comment by ghost** [comment]
@uudruid74 Thanks so much for this! the '-gpu swiftshader' fixed a lot of crashes i've been getting. Much appreciated!
