### ISSUE TITLE
strokeWidth doesn't work when using type: 'polygon'

### ISSUE THREAD

**Issue by fab1an** [nitaliano/react-native-mapbox-gl#435]
Documentation says `strokeWidth` should affect `polygon` and `polyline` but it works only for the latter.

(Android)

**Comment by Oblongmana** [comment]
+1 to this issue, but also on iOS!

I believe this may actually be an error in the documentation rather than a bug? Diving down a horrible rabbit hole of issues across multiple repos leads me to believe it may not be supported in the underlying library, but I'm having difficulty digesting it at 2am.

Other github issues I came across that might (?) be relevant:
https://github.com/mapbox/mapbox-gl-native/issues/324
https://github.com/mapbox/mapbox-gl-style-spec/issues/223
https://github.com/mapbox/mapbox-gl-native/issues/1737
https://github.com/mapbox/mapbox-gl-native/issues/837


Once I'm conscious again tomorrow, I'm likely going to attempt the approach of adding a separate `polyline` annotation for each polygon. Hopefully doesn't negatively impact performance
