### ISSUE TITLE
Click trough user location indicator

### ISSUE THREAD

**Issue by maqen** [nitaliano/react-native-mapbox-gl#463]
<img width="198" alt="" src="https://cloud.githubusercontent.com/assets/35422/20609293/ea08d10c-b28a-11e6-91df-c4b25345bffa.png">

The pin annotation in image is unclickable, can't click through the blue pulsating circle

Is there any way to circumvent this?

**Comment by markusekblad** [comment]
I'm having the same issue

**Comment by AdamJakiela** [comment]
+1

**Comment by esamelson** [comment]
Are you having this issue on iOS? It's an issue in the underlying Mapbox iOS SDK, and it was fixed in version 3.3.4. This component is using 3.3.1 currently. I was able to fix it by rerunning this module's `preinstall` script with 3.3.4 (or later) as the parameter. Note that you'll have to do this anytime you reinstall this module.

**Comment by JakielaAdam** [comment]
@esamelson I tried installing version 3.3.4 but it did not work for me. Perhaps I am running the preinstall script incorrectly. 

Are you just installing the package as usual and then running ` node ./scripts/download-mapbox-gl-native-ios-if-on-mac.js 3.3.4`?

Edit: I also re did the native install process in XCode.

**Comment by esamelson** [comment]
Hmm, it's been a little while since I've done this, but have you tried actually copying over the updated Mapbox.framework (from `node_modules/react-native-mapbox-gl/ios`) and replacing the one in your root project `ios` folder? For some reason a copy is made there during the initial install process, and I'm not sure that it gets automatically updated.

**Comment by JakielaAdam** [comment]
@esamelson That was it. Cheers!

**Comment by Kottidev** [comment]
i have same problem on IOS 

i can't click through the blue pulsating circle

how can i change size of pulsating circle ?

**Comment by ManAnRuck** [comment]
i have the same problem on iOS

**Comment by matthieupinte** [comment]
Hi, I have it too with iOS, trying with an update to `3.3.4`, the same issue.
