### ISSUE TITLE
Use GeoJSON coordinates for onTap and onLongPress

### ISSUE THREAD

**Issue by nitindhar7** [nitaliano/react-native-mapbox-gl#475]
I've noticed that the `onTap` and `onLongPress` hooks both return coordinates in this format: `[latitude, longitude]`, which is inconsistent with the [GeoJSON spec](https://tools.ietf.org/html/rfc7946). See:

> There MUST be two or more elements. The first two elements are longitude and latitude, or easting and northing, precisely in that order and using decimal numbers.

I'm storing coordinates in `[longitude, latitude]` format in my db (mongo), which uses the GeoJSON spec for its [geospatial query operators](https://docs.mongodb.com/v3.0/reference/operator/query-geospatial/) and didn't realize that Mapbox was returning them reversed, which was causing a bug in my backend service. Would be good to be spec complaint to reduce cryptic bugs from happening in client code and to integrate with other GIS tools seamlessly.

**Comment by tmcw** [comment]
Unfortunately the GeoJSON spec doesn't extend everywhere - [there are examples of both](http://www.macwright.org/lonlat/) orderings. But as far as I can see, react-native-mapbox-gl uses object properties, like `{ latitude, longitude }` rather than arrays. That appears to be the case given the onTap and onLongPress code I'm looking at right now: if it's not and you're seeing arrays - and using the latest version, feel free to re-open with more details.

**Comment by nitindhar7** [comment]
Apologize for this one. I misread the data format that I was receiving and so I closed this issue (would've deleted it if I couldve)
