### ISSUE TITLE
Using custom tiles

### ISSUE THREAD

**Issue by hamidhadi** [nitaliano/react-native-mapbox-gl#502]
How can I get custom tiles from my server?

**Comment by Lichwa** [comment]
@hamidhadi Did you figure out how to use custom tiles?

**Comment by RobertSasak** [comment]
See my answer in #630 .

**Comment by hamidhadi** [comment]
@RobertSasak Thank you. Is there any way to load custom vector tiles?

**Comment by RobertSasak** [comment]
I believe you need to provide url to your vector tiles source
```json 
"mapbox-streets": {
  "type": "vector",
  "url": "mapbox://mapbox.mapbox-streets-v6"
}
```
https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-vector

**Comment by smoll** [comment]
Hey @RobertSasak I noticed you mentioned you're using your own server to host mbtiles/rasters for download/accessing offline and was just wondering: have you had any luck pointing `react-native-mapbox-gl` at a local file instead of having it manage the download from a remote server for you? My use case is I'm already downloading a big zip file containing a bunch of things like images and other metadata, and it would be easier if I could just prepackage the offline-available tiles. Tried taking a look at the native code but I didn't see any place I could override a local path...

**Comment by RobertSasak** [comment]
I'm sorry I have not tried it myself. Perhaps you can use *file://* or *assets://*. I would start reading here
https://github.com/mapbox/mapbox-gl-native/issues/579
