### ISSUE TITLE
Android: n Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.MapView.onResume()' on a null object reference  

### ISSUE THREAD

**Issue by Kottidev** [nitaliano/react-native-mapbox-gl#526]
Hi ,

can you help me 

I don't know from when i have this issue 

![image](https://cloud.githubusercontent.com/assets/12915009/24710521/4208697a-1a15-11e7-96a7-6e5830090a7b.png)

Thanks

**Comment by benwalks** [comment]
Did you end up working this out @Kottidev?

**Comment by josdejong** [comment]
We have the same issue. It looks like it happens when mounting/unmounting a map a couple of times directly after each other. I haven't found a solution yet.

**Comment by benwalks** [comment]
@josdejong, I'm experimenting with the [5.0.2 SDK pull request](https://github.com/mapbox/react-native-mapbox-gl/pull/553) at the moment to see if it helps, will report back.

**Comment by josdejong** [comment]
Thanks Ben, would be glad to hear!

**Comment by benwalks** [comment]
Hi @josdejong, I didn’t have any luck with that PR.  How did you go finding a solution?

**Comment by josdejong** [comment]
Too bad. 

We didn't find a solution but implemented a workaround: on the page where we have the map, there where a couple of consecutive renders due to some async code for loading data and initializing everthing for the page. This causes this issue to occur. We implemented a flag which is false until _everything_ is initialized, and only then set the flag to true and render the map _once_.

**Comment by benwalks** [comment]
Thanks so much for letting me know @josdejong, that solution will work great for my app!

**Comment by josdejong** [comment]
:+1:

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If you see this issue there feel free to reopen
