### ISSUE TITLE
Black Map after download offline regions

### ISSUE THREAD

**Issue by marvinernst** [nitaliano/react-native-mapbox-gl#528]
Hey everybody,
after I downloaded an offline region on iOS  I get a black map for about 2 minutes. After this time everything works fine. This issue was encountered on mapbox-gl-native project some days ago and has already been fixed: [Issue](https://github.com/mapbox/mapbox-gl-native/issues/8518)

Will there be an update to this version of mapbox-gl-native in the near future to fix this error? Maybe this will also affect this issue #525

Thanks for any help.

Marvin

**Comment by butchmarshall** [comment]
Yes - I believe this is due to the `addOfflinePackProgressListener` emitting events even after maps are downloaded.

I notice once these events are finished emitting everything functions as expected.

This issues seems to go away in the master branch (mapbox sdk 4.2.2) but still present in the officially released 5.1.0 (mapbox sdk 4.1.1)
