### ISSUE TITLE
onTap and onOpenAnnotation both called

### ISSUE THREAD

**Issue by juiceo** [nitaliano/react-native-mapbox-gl#580]
The API seems to work in a way where tapping an annotation triggers both onTap and onOpenAnnotation. This makes it pretty hard to implement a feature where tapping an annotation opens some sort of overlay, and tapping elsewhere on the map closes the overlay (especially if you want to animate the open/close). The onTap event is also triggered before onOpenAnnotation, so there's really no way to find out if it was caused by tapping an annotation or not. 

Has somebody found a way to distinguish between these two types of onTap events easily? Is there a chance to change the API in a way where the onTap event would include information about an annotation being tapped as well?

Thanks!

**Comment by nolan-m** [comment]
I needed similar functionality as well.  I discovered in the docs there was a method that can fire when tapping on the annotation's callout.  (`tapOnCalloutForAnnotation`)  I hooked this up in iOS side and passed in a new handler to the MapView (`onAnnotationTapped`).  On the Android side, I discovered this function was already being called, but for `onRightAnnotationTapped`.   I ended up switching this to trigger my new function instead of `onRightAnnotationTapped` (since there is no right callout accessory in Android anyway).    You can leave the Android one alone if you prefer.  It should already fire `onRightAnnotationTapped` when you tap an annotation.

**Comment by nolan-m** [comment]
@lappalj4 See https://github.com/mapbox/react-native-mapbox-gl/pull/599 if you still need this functionality.

**Comment by oxygen0211** [comment]
Both handlers being calles is causing me a severe headache right now since it seems virtually impossible to support both tapping on an empty spot on the map and tapping on annotations but with distinguished actions. The action for tapping on an empty spot is always called. 

In my case, tapping on the map creates a new annotation and tapping on an annotation should edit it. While I can get into the editing handler, triggering it means that you pille up new annotations all around your original one which I in no case can ship to users. Also, this behavior will cause a bunch of side effects.

Am I missing something or is it really impossible to correct this behavior without implementing some complex (asynchronous) handling that will filter out the unwanted handler calls (which would totally suck to do)?

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.
