### ISSUE TITLE
Consider changing the way annotations are specified

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#623]
Annotations are specified through a property on `MapView`, in my opinion this is an unusual way of dealing with _another component_.

[Annotation itself is a component in the core](https://github.com/mapbox/react-native-mapbox-gl/blob/master/Annotation.js), take a polyline for example, the code would look much cleaner if it could also be used as component, [the way react-native-maps does](https://github.com/airbnb/react-native-maps/blob/master/example/examples/PolylineCreator.js#L78-L83), something like:

```jsx
<Annotation
  type="polyline"
  coordinates={coordinates}
  strokeColor="#00FB00"
  strokeWidth={4}
  strokeAlpha={.5}
/>
```

Also, the `coordinates` could be an array of objects instead of an array so the position of latitude/longitude wouldn't matter, fixing issues like #520:

```jsx
const coordinates = [
  ...
  {
    latitude: 40.76572150042782,
    longitude: -73.99429321289062,
  },
  ...
];
```

**Comment by aboeglin** [comment]
Also, I think the problem should be solved at the source, and the API should return [lat, lng] anyways. The convention tends to describe geopositions as latitude, longitude, elevation in that order. I know from a geometry point of view it doesn't make sense but it is like that. Or even better, the API would return a LatLng object directly. In any case I think the UI components need to be in sync with what the service returns to remove overhead of formatting data.

Other than that, I believe the whole project is being moved forward at the moment and the API is being improved.

**Comment by edwardgalligan** [comment]
> the coordinates could be an array of objects instead of an array so the position of latitude/longitude wouldn't matter

Generally speaking I would be inclined to agree here, except that `[lon, lat, alt?]` is what's conventionally returned by a number of serialisation formats (e.g. https://tools.ietf.org/html/rfc7946#section-3.1.1 ). I'd envisage most use-cases of annotations would be looping over input data, rather than being hand-coded by devs, so it would be nice to not have to run a transform operation on each coordinates array in these cases.

**Comment by nitaliano** [comment]
@aboeglin checkout [turf](http://turfjs.org/docs/) it has helper functions in there to deal with transforming your data to geojson

**Comment by aboeglin** [comment]
well, I have my service doing the transformation with a single map(), it's fairly easy to invert two values in an array with a length of 2. But still, it adds confusion and not needed code. In the outside world everybody uses lat,lng. In the dev world, people did weird things. But still, we should have a consistent experience across a solution. 

Mapbox offering a service with a certain type of data, it's better to stick to that format in the UI libraries depending on it I think. Therefore I believe the MapView's annotation should take [lng, lat], to match the API's format. If the underlying native components take it the other way, then maybe the component takes care of inverting the values, so that the interface makes more sense in regard with the Mapbox's API. Even though in the long run, the same format should be used across the whole solution to avoid 1 - unnecessary computations of converting formats 2 - clearer interfaces where the data is compatible all the way down to the UI.

**Comment by nitaliano** [comment]
Closing this out since the API will be strictly following the GeoJSON format.
