### ISSUE TITLE
How to add `onTap` to Polyline?

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#631]
I'm trying to add a `onTap` handler on annotations of `type: 'polyline'`, `onOpenAnnotation` seems to work only for `type: 'point'`, something that's not mentioned on the `README.md`.

Is this a bug or supposed to work that way? Is there a handler for tap events on `polyline`s?

**Comment by atarsha** [comment]
It is not possible due to an upstream issue that has been open for a very long time. https://github.com/mapbox/mapbox-gl-native/issues/2082

I worked around this in a somewhat hackish manner by doing an onTap callback on the MapView itself, then calculating the distance between the tap coordinate and every coordinate in every polyline (not efficient.) I then take the closest polyline coordinate to my tap (so long as it is within a given threshold of distance from my tap location) and drop a marker there so I could use the marker callout.

In order to make it behave well, I had to adjust the distance threshold I mentioned earlier based on current zoom level (further zoomed out, the threshold is larger)

This works, and works really well, but it's inefficient.

**Comment by lucasbento** [comment]
@atarsha: thanks for replying.

It's sad that there's no native way to do it, I'll try to implement what you said and see how it goes.

Thank you!

**Comment by nitaliano** [comment]
This is possible in v6 with a `LineLayer` and `queryRenderedFeaturesAtPoint`.

**Comment by lucasbento** [comment]
@nitaliano: how exactly do I do that?

The following code doesn't return the `LineLayer` even though I am clicking on it.
```js
  handleOnMapPress = async ({ geometry }) => {
    console.log(await this.map.queryRenderedFeaturesAtPoint(geometry.coordinates))
  }

// ... render()

<Map onPress={this.handleOnMapPress} />
```

Which returns only the stuff around the `LineLayer`:

![image](https://user-images.githubusercontent.com/6207220/32841297-392989dc-ca1a-11e7-9ad8-9aa8d93c13ff.png)
