### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#634]
I was trying to use the offline functions but they were merged 19 days ago and the latest release on npm is 2 months ago (5.2.0), would anybody be able to release the new version? Thanks!

**Comment by henrikra** [comment]
Yeah would be awesome to get 5.2.1 out to get all latest fixes on iOS. Example https://github.com/mapbox/react-native-mapbox-gl/pull/555 is still not released @nitaliano

**Comment by nitaliano** [comment]
I just tried to do a publish I don't have access to publish yet. I'll make sure I get added as an owner tomorrow and do a 5.2.1 publish.

**Comment by lucasbento** [comment]
Great, thanks @nitaliano!

**Comment by StasDoskalenko** [comment]
Hey, @nitaliano ! Could you please publish or at least merge with this PR? https://github.com/mapbox/react-native-mapbox-gl/pull/553

**Comment by nitaliano** [comment]
We're going to be scoping this package now so today I'll be doing a 5.2.2 release at `@mapbox/react-native-mapbox-gl` and https://github.com/mapbox/react-native-mapbox-gl/pull/553 will be included

**Comment by nitaliano** [comment]
@lucasbento @StasDoskalenko @henrikra It's been published - https://www.npmjs.com/package/@mapbox/react-native-mapbox-gl

Just a quick note since the namespace has changed you're going to need to unlink and relink the project to point to `@mapbox/react-native-mapbox-gl` instead of `react-native-mapbox-gl`, so at a high level

- Javascript imports `react-native-mapbox-gl` -> `@mapbox/react-native-mapbox-gl`
- Android build.gradle and settings.gradle need to point to `@mapbox/react-native-mapbox-gl`
- iOS Mapbox.framework and libRCTMapboxGL.a need to point to `@mapbox/react-native-mapbox-gl`

If you have any problems with the update please post back in this issue so we can squash them!

**Comment by henrikra** [comment]
@nitaliano I am getting 404 for that link
![image](https://user-images.githubusercontent.com/12229968/30557155-03e039f6-9cb6-11e7-86cc-c25e18a5d2a4.png)

**Comment by nitaliano** [comment]
@henrikra haha yes I just made it public

**Comment by henrikra** [comment]
Okay nice! Btw why namespace changed? :D

**Comment by nitaliano** [comment]
We wanted to move it under the mapbox org, so anyone at mapbox can publish a new version to npm

**Comment by henrikra** [comment]
Good thinking!

**Comment by lucasbento** [comment]
Awesome, thank you, @nitaliano!
