### ISSUE TITLE
[v6] Add compassEnabled prop on MapboxGL.MapView

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#694]
As a starting point for customization, it should be possible to hide and show the compass.

Moving forward, we probably also should be able to move the compass / assign our own PNG for for the compass icon, but I'd consider that out of the scope for a V1 release.

**Comment by nitaliano** [comment]
I've added support for `compassEnabled` in https://github.com/mapbox/react-native-mapbox-gl/pull/696 and I've added being able to add a custom compass icon to our backlog

**Comment by sugaith** [comment]
Is there a way to overwrite the onPress event of the compass?

If not, it is possible to do something like a custom compass with a ShapeSource and a SymbolLayer like
`<Mapbox.ShapeSource
            id="symbolLocationSource"
            shape={{
              type: 'Point',
              coordinates: stateLocation,
            }}
            onPress={() => {
              console.log("CUSTOM COMPASS PRESSED");
              console.log(map.current);
            }}>
            <Mapbox.SymbolLayer
              id="customCompassSymbol"
              style={{
                iconImage: locationMarkerIcon,
                iconSize: 1.2,
                iconAllowOverlap: true,
                iconRotate: 180,
                iconRotationAlignment: 'map',
                iconPitchAlignment: 'map',
              }}
            />
          </Mapbox.ShapeSource>`

But not completely because I cant set and "absolute position" for this, so that it stays fixed on the top-right like the native compass. Is there a way to do that?

If also not, it is really important to be able to grab the click event of a compass (callback) to other actions.

For example, I am using compass followHeading mode, then I want it to be canceled and tilted back to 90º and zoom out when I click the compass on the top right.
Well cant do that because there is no callback and no way to customize the compass button, so it make almost unfeasible to use this library in a deep way just because of this detail.

**Comment by sugaith** [comment]
@nitaliano how is this custom compass icon issue, any progress?

**Comment by nitaliano** [comment]
I don't maintain this anymore this is the new repo https://github.com/react-native-mapbox-gl/maps
