### ISSUE TITLE
[v6] LineLayer runtime style crash if layer is already defined in base style

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#704]
If a `LineLayer` is already defined in a base style, runtime styles attempting to override the base style crashes the application.

See [this fork](https://github.com/kristfal/react-native-mapbox-gl/blob/v6/example/src/components/CustomVectorSourceIssue.js) for code reproduction where `osmCloastlineBlur` layer is already defined in base source.

**Comment by nitaliano** [comment]
@kristfal a few things are happening here. For some reason that source you are providing is named `root` instead of `composite`, so when the native code is looking up source it cannot find it.

I've added some code locally to check if the source exists and just reuse it and your example would work, but you would also need to add an id to the VectorSource

```javascript
<MapboxGL.VectorSource id='root'>
      <MapboxGL.LineLayer
           id='osmCoastlineBlur'
           sourceLayerID='land'
           style={...} />
</MapboxGL.VectorSource>
```

I think it's time for me to start going through the code and adding some useful exceptions.

**Comment by nitaliano** [comment]
I added the updates needed in this PR https://github.com/mapbox/react-native-mapbox-gl/pull/705

**Comment by kristfal** [comment]
Thanks for the feedback. Confirming that it now works with latest PR.
