### ISSUE TITLE
onChangeUserTrackingMode missing from V6

### ISSUE THREAD

**Issue by RNMBuser** [nitaliano/react-native-mapbox-gl#742]
When moving the map, it is impossible to know that UserTrackingMode has changed.

**Comment by nitaliano** [comment]
It's going to be added to our `6.0.1` release this week

**Comment by nitaliano** [comment]
I'm going to hold off on putting this into `6.0.1` Android is moving towards using the `LocationLayerPlugin` and there is not native support for this callback, so it will be interesting getting this added

**Comment by RNMBuser** [comment]
It will be of great help if you could add it to iOS, even if it's not done and not documented, since I need it urgently for an iOS app.

**Comment by RNMBuser** [comment]
I'll elaborate as to why I think this is urgent.
Suppose you have an app that has a button that allows user to center map on current position. There cannot be indication when the user moves the map, since the animated property on regionDidChange is true if the user pushes the map and does not hold it after the move.

This is critical when using properties on React Native (there's no way to force a property if it didn't change before) and even more critical using Redux.

**Comment by hernanmateo** [comment]
Hello @RNMBuser @nitaliano ,
I also have the same problem and in the meantime I have created a fork that implements this functionality only for iOS (as I only use this repository to this platform). Be carefull because it does not work exactly in the same way as in v5 since in this case it triggers ALL the changes that occur and in the previous version (v5) only returns those produced by the 'system' (excluding the events that occurred at startup and those that are fired from react-native). So, it's up to you to filter these events in the javascript thread).

You can find it in the master branch on my fork (from release/6.0.1) https://github.com/hernanmateo/react-native-mapbox-gl

ex. I use this event to set the location to None when the user moves the map:

```js
<Mapbox.MapView
        ref={(c) => this._map = c}
        id="mainMapView"
        maxZoomLevel={22}
        showUserLocation={true}
        styleURL={mapType}
        userTrackingMode={this.state.userTrackingMode}
        userLocationVerticalAlignment={Mapbox.UserLocationVerticalAlignment.Center}
        onChangeUserTrackingMode={this._onChangeUserTrackingMode.bind(this)}
        compassEnabled={true} >
</Mapbox.MapView>

_onChangeUserTrackingMode(userTrackingMode) {
    if(userTrackingMode == Mapbox.UserTrackingModes.None) {
      this.setState({
           userTrackingMode: userTrackingMode
      })
    }
 }
````
I hope it's useful for you and I also hope that Mapbox adds this functionality soon to the official repository

**Comment by nitaliano** [comment]
Closing this out. I created a new issue that has combined a few tickets follow along there, but this is in active development https://github.com/mapbox/react-native-mapbox-gl/issues/881

**Comment by nitaliano** [comment]
Support has been added in this PR https://github.com/mapbox/react-native-mapbox-gl/pull/897

**Comment by nitaliano** [comment]
This has been merged into master
