### ISSUE TITLE
[BUG] userTrackingWithHeading disappear after user scroll

### ISSUE THREAD

**Issue by Jose4gg** [nitaliano/react-native-mapbox-gl#780]
If I have the user track mode set with heading and I try to zoom, scroll or rotate the map the annotation is reset to the normal blue point.

**Comment by nitaliano** [comment]
I'm seeing this on iOS, Android seems okay

**Comment by nitaliano** [comment]
@Jose4gg it seems to be the expected behavior https://www.mapbox.com/ios-sdk/api/3.6.4/Enums/MGLUserTrackingMode.html#/c:@E@MGLUserTrackingMode@MGLUserTrackingModeFollow since that is really expected to be used by the nav sdk there's not much we can do about that here.

What I would recommend doing and I will eventually have a UI pack done for common layers is to create a `ShapeSource` and have a `CircleLayer` and `SymbolLayer` then you will have full control over this. Doing in this way also gives you the ability to work with the RN Animated API and update the source very nicely like in this example https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/DriveTheLine.js. You can listen for GPS updates with https://facebook.github.io/react-native/docs/geolocation.html

```
<MapboxGL.ShapeSource id='nav-icon-source' shape={...}>
   <MapboxGL.CircleLayer id='nav-icon-circle-shadow' style={...} />
   <MapboxGL.CircleLayer
       id='nav-icon-circle'
      aboveLayerID='nav-icon-circle-shadow'
      style={...} />
   <MapboxGL.SymbolLayer
      id='nav-icon-arrow-symbol'
      aboveLayerID='nav-icon-circle
      style={...} />
</MapboxGL.ShapeSource>
```
