### ISSUE TITLE
[ANDROID] User location rendering behind Shapes

### ISSUE THREAD

**Issue by Jose4gg** [nitaliano/react-native-mapbox-gl#796]
On IOS the user location is always on Top, but on Android is different. I think should be equal on both and should be always on top.

![](https://dl2.pushbulletusercontent.com/4R6xzl5mPTcpYSbkMyKiznIVfFz5dWOr/Screenshot_20171122-113341.png)

**Comment by nitaliano** [comment]
Agreed. The Android and iOS SDK are both rendering the user location different.

The Android SDK is loading the user location as a layer, and on iOS it's loaded as an AnnotationView. What we could probably do for Android is just default the user location layer to always be the top layer(0 index).

One thing to note about this is since Android is using a layer to render this all AnnotationView's will always be on top of layers. Which could be an ok solution since we're trying to move aways from AnnotationView in favor of layers.

To get around this for now you could try to position your layers below the user location layer for Android only. These are the layer id's that are used https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerConstants.java#L22 depending on what your userTrackingMode is set too.

**Comment by Jose4gg** [comment]
Perfect, thank you as always!

**Comment by nitaliano** [comment]
The fix for this will be added to this PR https://github.com/mapbox/react-native-mapbox-gl/pull/897 it's still a TODO just wanted to update the ticket

**Comment by nitaliano** [comment]
PR has been merged into master so if you add a layer without `aboveLayerID`, `belowLayerID`, or `layerIndex` we do a check and make sure we put the layer below the user icon. Feel free to reopen if you run into any bugs
