### ISSUE TITLE
onRegionIsChaning vs onRegionDidChange

### ISSUE THREAD

**Issue by kaynz** [nitaliano/react-native-mapbox-gl#809]
Hey,

what is the difference between onRegionIsChanging and onRegionDidChange?

I would expect onRegionDidChange to fire when the User stops dragging (=release finger) the map. Actually both listeners seem to behave same, fire while dragging.

**Comment by nitaliano** [comment]
`onRegionIsChanging` should fire while dragging the map and `onRegionDidChange` should fire once the region is done changing.  The problem is on Android `onRegionDidChange` gets fired even while dragging the map, but on iOS `onRegiondDidChange` only gets called once the camera is done moving. We have a bug open in gl-native for it https://github.com/mapbox/mapbox-gl-native/issues/10337
