### ISSUE TITLE
Add more information to offline packs

### ISSUE THREAD

**Issue by nitaliano** [nitaliano/react-native-mapbox-gl#829]
We have more information on the native side, so we should add it to our JSON that we send up to the JS. 

From the tickets I've been reading it looks like we should add
* status(download status)
* countOfResourcesExpected
* maximumResourcesExpected
* countOfResourcesCompleted
* countOfBytesCompleted

**Comment by josenaves** [comment]
Hey @nitaliano, for getPack, we have something like this:

```
{ pack: { 
    metadata: '{"name":"SFO_SATELLITE_0"}',
    bounds: [ [ -121.530762, 38.61687 ], [ -121.536255, 38.612578 ] ] 
  }, _metadata: null }
```

What about this:

```
{ pack: { 
    metadata: {
      "name":"SFO_SATELLITE_0",
      "downloadStatus": 1,
      "countOfResourcesExpected": 70000,
      "maximumResourcesExpected": 1232123432,
      "countOfResourcesCompleted": 3500,
       "countOfBytesCompleted": 12122
    }',
    bounds: [ [ -121.530762, 38.61687 ], [ -121.536255, 38.612578 ] ] 
  }
 }
```

**Comment by nitaliano** [comment]
@josenaves looks great!

**Comment by josenaves** [comment]
@nitaliano it turns out that we have a non exposed native method called getStatus.
So, I'm exposing it as getPackStatus method on JS side.

I had a hard time testing it. But, it's working

I'm opening a PR right now. I know that documentation and tests are missing for it.

Could you please take a look at my PR ?
https://github.com/mapbox/react-native-mapbox-gl/pull/836

**Comment by nitaliano** [comment]
Closing this out it's in `6.0.2`
