### ISSUE TITLE
`onSetCameraComplete` not being called

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#838]
I'm using `setCamera` as soon as `onDidFinishLoadingMap`  fires to center the map on specific coordinates:

```js
      return this.map.setCamera({
          bounds: {
            paddingTop: 30,
            paddingRight: 30,
            paddingBottom: 15,
            paddingLeft: 30,
          },
          ne: [northEastCoordinates.longitude, northEastCoordinates.latitude],
          sw: [farthestCoordinate.longitude, farthestCoordinate.latitude],
        },
      })
```

After finishing it doesn't call `onSetCameraComplete` callback specified in `MapView`.

**Comment by lucasbento** [comment]
@nitaliano: ~~still on that, can't the `setCamera` and other [MapView methods](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/MapView.md#methods) return promises?~~

~~A simple callback on the last argument of the function would be good if this can't be done now.~~

**Edit:** [nevermind, it already does 🎉](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/RCTMGL/RCTMGLMapViewManager.m#L191-L194)

**Comment by lucasbento** [comment]
`await`ing `setCamera` works, `onSetCameraComplete` doesn't.

**Comment by nitaliano** [comment]
@lucasbento `onSetCameraComplete` was the initially way this was designed since on Android you can't pass blocks around the way you can on iOS. Since then I've monkey patched Android to emit a callback and the js converts that to a promise, so all methods can be awaited on if they goto the native side.

I'll make sure to remove this from the examples and docs find and replace all
