### ISSUE TITLE
[v6] Telemetry service timeout error (Android)

### ISSUE THREAD

**Issue by hernanmateo** [nitaliano/react-native-mapbox-gl#878]
**RN**: 0.50.3
**Android**: 7.0
**MapboxGL**: 6.0.2

Hi,
I'm not sure if I'm doing something bad or it's an error in mabox component. The fact is that when I force to close the application and then open it quickly I'm receiving this message and then the app closes (I'm receiving this timeout even if I don't reopen the app):

> 12-14 18:14:53.553  2500  2532 W ActivityManager: Timeout executing service: ServiceRecord{41cab15 u0 com.devstep.compaz/com.mapbox.services.android.telemetry.service.TelemetryService}

It seems that the telemetry service remains open after closing the application.

**Comment by Jose4gg** [comment]
+1 Same here!

**Comment by AndroidDeveloperMCT** [comment]
Same issue with me

**Comment by Jose4gg** [comment]
@nitaliano Hey man, any updates on this?

**Comment by nitaliano** [comment]
We should not be crashing the application here that is not the expected behavior and that will be looked in to.

As for the telemetry service staying open that is the intended behavior and this [comment](https://github.com/mapbox/mapbox-gl-native/issues/10503#issuecomment-346202145) sums it up very nicely.

Let me know if there are any questions regarding the crash or the comment that I linked above

**Comment by Jose4gg** [comment]
@nitaliano I tested something and it's a 50% work, on the `RCTMGLMapViewManager.java` on the `onDropViewInstance` method I added a `mapView.onDestroy();` so right now if before closing the app I unmount the component the issue is gone, but the problem persists if I close the app using the MapView. Do you have any thought on it?

**Comment by nitaliano** [comment]
Interesting that to me says, that we're most likely not hitting this line https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java#L895 which is what should be calling `onDestroy` in this case

**Comment by parkdcom** [comment]
We're experiencing the same issue. In some cases we get an ANR caused by the TelemetryService after closing the app and opening it again.

**Comment by hernanmateo** [comment]
For the while I have avoided this problem by exposing and disabling the telemetry service attribute.

**Comment by nitaliano** [comment]
I cannot reproduce this issue with master, but can reproduce it with 6.0.2 everytime. Would someone mind testing this out?

I tested this out with my Pixel running 7.0.0

**Comment by pohnean** [comment]
@hernanmateo care to share how you did expose and disable the telemetry service attribute?

**Comment by sironjuh** [comment]
@nitaliano 

We were still experiencing this with master as well. As for now, we've had to disable the telemetry on Android to not cause the crash.

**Comment by jesusmartinoza** [comment]
@pohnean To disable Telemetry 
```
Mapbox.getInstance(getApplicationContext(), getString(R.string.mapbox_public_token));
MapboxTelemetry.getInstance().setTelemetryEnabled(false);
```

**Comment by hannta** [comment]
I got similar issue, almost 50% of times when I open the app, it ARN's with error:

```
02-23 09:38:40.886: E/ActivityManager(1414): ANR in com.my.app
02-23 09:38:40.886: E/ActivityManager(1414): Reason: executing service com.my.app/com.mapbox.services.android.telemetry.service.TelemetryService
```
```
02-23 09:38:51.018: W/ActivityManager(1414): Service crashed 2 times, stopping: ServiceRecord{a7478ea u0 com.my.app/com.mapbox.services.android.telemetry.service.TelemetryService}, avgRestartTime: 9223372036854775807
```

Im using:
RN: 0.52.2
mapbox-gl: 6.0.3-rc1
Android: 8

**Comment by jesusmartinoza** [comment]
@hannta yep, it's a known issue. Please disable Telemetry

**Comment by nitaliano** [comment]
This should not be an issue anymore with `6.1.0` you should not experience an ANR, the telemetry service is going to stay open it is in the terms or service. If someone runs into this with `6.1.0` reopen please

**Comment by gmaclennan** [comment]
@jesusmartinoza would you mind sharing where I can add those lines for disabling telemetry? I don't have a lot of Android developer experience - I'm developing the app in react-native. We are seeing random crashes after about 5 mins and it seems to be related to the telemetry service when the phone does not have an internet connection. I'd like to try disabling it to narrow down where the problem is coming from.
