### ISSUE TITLE
Re-download of iOS sdk everytime with yarn

### ISSUE THREAD

**Issue by mtt87** [nitaliano/react-native-mapbox-gl#916]
When you install a new npm module with `yarn` every time it's triggered `postinstall`
https://github.com/mapbox/react-native-mapbox-gl/blob/master/package.json#L29

<img width="577" alt="screen shot 2017-12-29 at 11 34 04" src="https://user-images.githubusercontent.com/2150927/34435321-f195584a-ec8c-11e7-919f-695f881109c3.png">

The download coming from `https://mapbox.s3.amazonaws.com/...` is extremely slow, even on a 100mbit fibre line I get ~200kbs max speed.

Not sure if this happens with `npm` as well but I suspect it does.

Better way would be to double check if the file is already there not download it twice, otherwise put the sdk on cloudfront or something with more bandwidth.

**Comment by nitaliano** [comment]
We create a `.framework_version` file once we download the SDK, and inside our script we check to see if you already have that SDK downloaded locally https://github.com/mapbox/react-native-mapbox-gl/blob/master/scripts/download-mapbox-gl-native-ios.sh#L8 that is the expected behavior, will need to test it out with yarn to see what going on

**Comment by nagad814** [comment]
Facing with the same issue.

**Comment by nitaliano** [comment]
Maybe moving the download off of s3 and grabbing it from the releases on Github might help speed things up https://github.com/mapbox/mapbox-gl-native/releases

**Comment by kristfal** [comment]
Hey,

in an effort to clean out old tickets, I'm closing this one. We got a PR (#1533) open to move the iOS native SDK installation to cocoapods. This move should resolve the issue.
