### ISSUE TITLE
Problem Selecting Point Annotation Twice

### ISSUE THREAD

**Issue by JakielaAdam** [nitaliano/react-native-mapbox-gl#937]
Hello,

I have a MapView with several PointAnnotations which are clickable. When the user presses a PointAnnotation, I use the `onSelected` callback display a custom overlay on the map. This overlay has a close button which removes it from the view and displays the map just as before. 

My problem arises is the user performs the following steps:

1. Presses a PointAnnotation to display the overlay view. 
2. The view is displayed and after some time, the user presses the close button to remove the view.
3. The user then presses the same PointAnnotation to redisplay the view. 

**The problem is, the `onSelected ` callback is not being called on step 3 because it was the last point annotation to be pressed (in step 1).** However, if the user presses a different marker on step, all works as normal and the callback is called. This only happens when a marker is pressed two times in a row. 

Is there a way I can work around this? Do I need to manually tell the map to deselect the PointAnnotation when the user closes the overlay in step 2?

**Comment by nitaliano** [comment]
Thanks for reporting we'll be looking into it
  
You might be able to work around it by messing with the `selected` bool property on the PointAnnotations. I think we'll need to add a `deselect` method on the PointAnnotation component so when you close the popup manually you could call something like `annotationRef.deselect()`

**Comment by JakielaAdam** [comment]
@nitaliano Hi. Sorry for taking so long to respond. I tried setting selected to false using a reference to the point annotation but still get the same behavior.

**Comment by edolix** [comment]
Hello @nitaliano !

I've a similar issue with PointAnnotations and Callout that i'm using as markers on Map.

The problem comes out after playing a bit with the map. 
Tap some callouts, make zoom in & out and then... the PointAnnotation's onSelected method is never fired up.
It's weird because if i tap NEAR the PointAnnotation (some pixels around it) the callout comes out. It seems the PointAnnotation's view is not "centered" with the touchable area.

You can try the real [app](https://itunes.apple.com/it/app/cammino-delle-apparizioni/id1387790972?mt=8) on the AppStore. 
Steps to reproduce:

- Open the map and click one of the five buttons in the header to load the route with the markers.
- Drag the map / Tap the markers / Zoom in&out (IMPORTANT: do not trigger re-render changing the current route)
- After playing a bit you can see the tap on markers does not open the default overlay view.
- If you change the current route - using buttons on header - everything'ss come back working again. (because components were updated)

Thanks!

**Comment by sroze** [comment]
> I think we'll need to add a deselect method on the PointAnnotation component so when you close the popup manually you could call something like annotationRef.deselect()

Maybe the best idea is to have a `onTouch` which will not consider is a "selected", while the `onSelected` would :)

**Comment by kristfal** [comment]
Hey,

in an effort to clean out old open tickets, I'm closing this one.

Point annotations/callaout support is now removed from the native libs. This lib will follow suit when 7.0.0 arrives. I'd recommend using a ShapeSource and handling callouts manually in the RN side of things instead as a workaround.

**Comment by iromjkee** [comment]
@kristfal @JakielaAdam Hi, so is there any new functionality to "deselect" `PointAnnotation`? Or where I can check for such info

**Comment by AWZRD** [comment]
Not sure if anybody runs into this but wrapping the `PointAnnotation` in a `TouchableOpacity` should do the trick
