### ISSUE TITLE
Undocumented types

### ISSUE THREAD

**Issue by cglacet** [nitaliano/react-native-mapbox-gl#974]
The actual state of the documentation is really unclear on what types are accepted for different style properties. For example, in [`MapboxGL.LineLayer`'s documentation](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/LineLayer.md), if you have a look at [`lineCap`](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/LineLayer.md#styles) the type you can see for now is `enum` which is probably wrong as I guess it means `an item from an enum`, but what would be nice is to have the actual expected type, ie. the enum's content (I guess it's something like "butt"| "round"| "square" as it used to be). 

Another type that is wrong is, for example, the `lineOpacity` that is currently typed as `number` but it also accept a function `(stops, mode) => MapStyleFunctionItem` (one would need to add a link to the `stop` and `mode` types too). Changing the type here would also allow to add a link to [this page](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/StyleSheet.md) 
 which is not referenced in `LineLayer`'s page for now.  

PS, Isn't it possible to simple use the classic styles that are used [here](https://www.mapbox.com/mapbox-gl-js/style-spec/)? That would simplify porting for the users and you wouldn't have to re-write another documentation for something that is more or less similar.

**Comment by nitaliano** [comment]
@cglacet we are planning on revising the documentation in an upcoming release, and I do want to give this repo a proper doc site like other popular open source repos. The docs are currently generated from the style spec. 

All of those values exist under `MapboxGL` so in the case of `lineCap` we have
* `MapboxGL.LineCap.Butt`
* `MapboxGL.LineCap.Round`
* `MapboxGL.LineCap.Square`

If you wanted to see all enum values check here
* Android - https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java#L53
* iOS - https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/RCTMGL/MGLModule.m#L25
* Mapbox Layer Style React Props - https://github.com/mapbox/react-native-mapbox-gl/blob/master/javascript/utils/styleMap.js#L197

One of the main reasons we don't just allow providing `butt | round | square` for example is because the values in the Android SDK are for the most part String values, and the iOS SDK for the most part is Number values, they don't directly map to the values in the style spec so we would need a converter on each of the native sides that would need to be hand written to parse all of the style properties, which could be hard to maintain. All of the style code is autogenerated on all of our platforms

I'll leave this open until we update our docs and we can use this issue for any further discussion on how to make the documentation better.

**Comment by nitaliano** [comment]
I'm going to close this out we're tracking this work in https://github.com/mapbox/react-native-mapbox-gl/issues/756
